-- MySQL Script generated by MySQL Workbench
-- Sun Mar 10 12:20:13 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Departamento` (
  `id_Departamento` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  PRIMARY KEY (`id_Departamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Provincia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Provincia` (
  `id_Provincia` INT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Departamento_id_Departamento` INT NOT NULL,
  PRIMARY KEY (`id_Provincia`, `Departamento_id_Departamento`),
  INDEX `fk_Provincia_Departamento1_idx` (`Departamento_id_Departamento` ASC),
  CONSTRAINT `fk_Provincia_Departamento1`
    FOREIGN KEY (`Departamento_id_Departamento`)
    REFERENCES `mydb`.`Departamento` (`id_Departamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Distrito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Distrito` (
  `id_Distrito` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `Provincia_id_Provincia` INT NOT NULL,
  PRIMARY KEY (`id_Distrito`, `Provincia_id_Provincia`),
  INDEX `fk_Distrito_Provincia1_idx` (`Provincia_id_Provincia` ASC),
  CONSTRAINT `fk_Distrito_Provincia1`
    FOREIGN KEY (`Provincia_id_Provincia`)
    REFERENCES `mydb`.`Provincia` (`id_Provincia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Clinerte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Clinerte` (
  `id_Clinerte` INT NULL,
  `Tipo_Documento` VARCHAR(45) NULL,
  `Nombre` VARCHAR(45) NULL,
  `dIRECCION` VARCHAR(45) NULL,
  `Distrito_id_Distrito` INT NOT NULL,
  PRIMARY KEY (`Distrito_id_Distrito`, `id_Clinerte`),
  CONSTRAINT `fk_Clinerte_Distrito1`
    FOREIGN KEY (`Distrito_id_Distrito`)
    REFERENCES `mydb`.`Distrito` (`id_Distrito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Comprobante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Comprobante` (
  `id_Comprobante` INT NOT NULL,
  `Nombre_Comprobante` VARCHAR(45) NULL,
  PRIMARY KEY (`id_Comprobante`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Empleado` (
  `id_Vendedor` INT NOT NULL,
  `nombre_Vendedor` VARCHAR(45) NULL,
  PRIMARY KEY (`id_Vendedor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`VENTAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`VENTAS` (
  `idVENTAS` INT NOT NULL,
  `VENTAScol` VARCHAR(45) NULL,
  `Clinerte_Distrito_id_Distrito` INT NOT NULL,
  `Clinerte_id_Clinerte` INT NOT NULL,
  `Comprobante_id_Comprobante` INT NOT NULL,
  `Empleado_id_Vendedor` INT NOT NULL,
  PRIMARY KEY (`idVENTAS`, `Clinerte_Distrito_id_Distrito`, `Clinerte_id_Clinerte`, `Comprobante_id_Comprobante`, `Empleado_id_Vendedor`),
  INDEX `fk_VENTAS_Clinerte1_idx` (`Clinerte_Distrito_id_Distrito` ASC, `Clinerte_id_Clinerte` ASC),
  INDEX `fk_VENTAS_Comprobante1_idx` (`Comprobante_id_Comprobante` ASC),
  INDEX `fk_VENTAS_Empleado1_idx` (`Empleado_id_Vendedor` ASC),
  CONSTRAINT `fk_VENTAS_Clinerte1`
    FOREIGN KEY (`Clinerte_Distrito_id_Distrito` , `Clinerte_id_Clinerte`)
    REFERENCES `mydb`.`Clinerte` (`Distrito_id_Distrito` , `id_Clinerte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VENTAS_Comprobante1`
    FOREIGN KEY (`Comprobante_id_Comprobante`)
    REFERENCES `mydb`.`Comprobante` (`id_Comprobante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_VENTAS_Empleado1`
    FOREIGN KEY (`Empleado_id_Vendedor`)
    REFERENCES `mydb`.`Empleado` (`id_Vendedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Producto` (
  `id_Producto` INT NOT NULL,
  `Categoria` VARCHAR(45) NULL,
  `Descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`id_Producto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Detalle_Ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Detalle_Ventas` (
  `id_Detalle_Comprobantes` INT NULL,
  `Id_Detalle` VARCHAR(45) NULL,
  `Precio` VARCHAR(45) NULL,
  `Cantidad` VARCHAR(45) NULL,
  `Total_Producto` VARCHAR(45) NULL,
  `Producto_id_Producto` INT NOT NULL,
  `VENTAS_idVENTAS` INT NOT NULL,
  UNIQUE INDEX `Id_Detalle_UNIQUE` (`Id_Detalle` ASC),
  UNIQUE INDEX `id_Detalle_Comprobantes_UNIQUE` (`id_Detalle_Comprobantes` ASC),
  PRIMARY KEY (`Producto_id_Producto`, `VENTAS_idVENTAS`),
  INDEX `fk_Detalle_Ventas_VENTAS1_idx` (`VENTAS_idVENTAS` ASC),
  CONSTRAINT `fk_Detalle_Ventas_Producto1`
    FOREIGN KEY (`Producto_id_Producto`)
    REFERENCES `mydb`.`Producto` (`id_Producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Detalle_Ventas_VENTAS1`
    FOREIGN KEY (`VENTAS_idVENTAS`)
    REFERENCES `mydb`.`VENTAS` (`idVENTAS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Detalle_Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Detalle_Producto` (
  `id_Detalle` INT NOT NULL,
  `Precio` VARCHAR(45) NULL,
  `Fecha_Inicio` DATE NULL,
  `Fecha_Final` DATE NULL,
  `Producto_id_Producto` INT NOT NULL,
  PRIMARY KEY (`id_Detalle`, `Producto_id_Producto`),
  INDEX `fk_Detalle_Producto_Producto_idx` (`Producto_id_Producto` ASC),
  CONSTRAINT `fk_Detalle_Producto_Producto`
    FOREIGN KEY (`Producto_id_Producto`)
    REFERENCES `mydb`.`Producto` (`id_Producto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sede`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Sede` (
  `id_Sede` INT NOT NULL,
  `Nombre` VARCHAR(45) NULL,
  `Direcion` VARCHAR(45) NULL,
  `Distrito_id_Distrito` INT NOT NULL,
  `Distrito_Provincia_id_Provincia` INT NOT NULL,
  PRIMARY KEY (`id_Sede`, `Distrito_id_Distrito`, `Distrito_Provincia_id_Provincia`),
  INDEX `fk_Sede_Distrito1_idx` (`Distrito_id_Distrito` ASC, `Distrito_Provincia_id_Provincia` ASC),
  CONSTRAINT `fk_Sede_Distrito1`
    FOREIGN KEY (`Distrito_id_Distrito` , `Distrito_Provincia_id_Provincia`)
    REFERENCES `mydb`.`Distrito` (`id_Distrito` , `Provincia_id_Provincia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vendedor_Sede`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Vendedor_Sede` (
  `id_Sede` INT NULL,
  `Sede_Distrito_id_Distrito` INT NOT NULL,
  `Sede_Distrito_Provincia_id_Provincia` INT NOT NULL,
  `Empleado_id_Vendedor` INT NOT NULL,
  PRIMARY KEY (`id_Sede`, `Sede_Distrito_id_Distrito`, `Sede_Distrito_Provincia_id_Provincia`, `Empleado_id_Vendedor`),
  INDEX `fk_Vendedor_Sede_Empleado1_idx` (`Empleado_id_Vendedor` ASC),
  CONSTRAINT `fk_Vendedor_Sede_Sede1`
    FOREIGN KEY (`id_Sede` , `Sede_Distrito_id_Distrito` , `Sede_Distrito_Provincia_id_Provincia`)
    REFERENCES `mydb`.`Sede` (`id_Sede` , `Distrito_id_Distrito` , `Distrito_Provincia_id_Provincia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Vendedor_Sede_Empleado1`
    FOREIGN KEY (`Empleado_id_Vendedor`)
    REFERENCES `mydb`.`Empleado` (`id_Vendedor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
